In [1]:
import torch

torch.__version__

'1.13.0+cpu'

In [2]:
torch.empty(5, 3)

tensor([[1.5554e-43, 1.5975e-43, 1.3873e-43],
        [1.4574e-43, 1.4013e-44, 1.4013e-44],
        [1.6255e-43, 1.5554e-43, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44],
        [1.3312e-43, 1.3312e-43, 1.6535e-43]])

In [3]:
torch.rand(5, 3)

tensor([[0.5417, 0.5486, 0.8198],
        [0.8018, 0.6830, 0.7348],
        [0.3726, 0.1647, 0.9812],
        [0.2837, 0.5999, 0.8046],
        [0.6997, 0.0729, 0.6543]])

In [7]:
x_data = torch.Tensor([[1.0], [2.0], [3.0]])
y_data = torch.Tensor([[2.0], [4.0], [6.0]])


class LinearModel(torch.nn.Module):  #从Module继承
    #必须实现以下两个函数
    #初始化
    def __init__(self):
        super().__init__()  #调用父类的初始化
        self.linear = torch.nn.Linear(1, 1)  #构造一个对象，包含权重和偏置
        #Linear的参数为，输入的维度（特征数量，不是样本数量）和输出的维度，以及是否有偏置(默认为True)

    #前馈过程中进行的计算
    def forward(self, x):  #这里实际上是一个override
        y_pred_1 = self.linear(x)  #在这里计算w * x + b 线性模型
        return y_pred_1
    #不需要自己写反馈


model = LinearModel()  #这里的model是callable可调用的 调用方法为:model(x)

criterion = torch.nn.MSELoss()  #是否要求均值
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(1000):
    y_pred = model(x_data)
    loss = criterion(y_pred, y_data)
    if epoch % 100 == 0:
        print(epoch, loss.item(), y_pred.data)

    optimizer.zero_grad()  #梯度归零
    loss.backward()
    optimizer.step()  #根据梯度和预先设置的学习率自动更新
print(model.linear.weight.item(), model.linear.bias.item())

0 32.22322082519531 tensor([[-0.3216],
        [-1.1760],
        [-2.0305]])
100 0.19908487796783447 tensor([[2.6598],
        [4.1416],
        [5.6233]])
200 0.12302225828170776 tensor([[2.5187],
        [4.1113],
        [5.7039]])
300 0.07602027803659439 tensor([[2.4077],
        [4.0875],
        [5.7673]])
400 0.04697592929005623 tensor([[2.3205],
        [4.0688],
        [5.8171]])
500 0.029028264805674553 tensor([[2.2520],
        [4.0541],
        [5.8562]])
600 0.0179376769810915 tensor([[2.1981],
        [4.0425],
        [5.8869]])
700 0.011084397323429585 tensor([[2.1557],
        [4.0334],
        [5.9111]])
800 0.006849481258541346 tensor([[2.1224],
        [4.0263],
        [5.9301]])
900 0.004232556093484163 tensor([[2.0962],
        [4.0206],
        [5.9451]])
1.9406023025512695 0.13502514362335205


In [5]:
class C1:
    def __init__(self, x):
        self.x = x

    def func1(self, a):
        return 2 * a + self.x

    def func2(self):
        print("I am func2")
        return self.x

    def __call__(self, u):
        print('i can called like a function')
        return self.func1(u)


class C2(C1):
    def __init__(self, x, y):
        self.x = 0
        super().__init__(y)

    def func1(self, a):
        return 3 * a + self.x


mod = C2(1, 2)
mod1 = C1(1)
# test = mod.func1(3)
# print(test)
print(mod(10))
test = mod.func2()
print(test)

i can called like a function
32
I am func2
2


In [8]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[1.9406]])),
             ('linear.bias', tensor([0.1350]))])

In [10]:
list(model.named_parameters())

[('linear.weight',
  Parameter containing:
  tensor([[1.9406]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([0.1350], requires_grad=True))]

In [11]:
torch.save(model.state_dict(), 'bn.pt')

In [13]:
bn_state_dict = torch.load('bn.pt')
print(bn_state_dict)

OrderedDict([('linear.weight', tensor([[1.9406]])), ('linear.bias', tensor([0.1350]))])
